### ISSUE TITLE
NullReferenceException on blocked task when original task faulted

### ISSUE THREAD

**Issue by rgueldenpfennig** [TurnerSoftware/CacheTower#192] opened 2021-11-04 15:47 UTC
### What does the bug do?

Imagine two tasks accessing the CacheTower API to `GetOrSet` a cache key at the same time. The second call will be "blocked" by waiting for the task completion source to complete.
The initial task is executing the `getter` function in the meantime. The `getter` is throwing an exception which is bubbling up to the first task.
But the second task is provoking a `NullReferenceException` because the result of the task completion source is set to `Null`.

As far as I understand is the problem in line 346 of the CachStack class.

https://github.com/TurnerSoftware/CacheTower/blob/2e3ac6d1789c283795686c3cfabc17537776567b/src/CacheTower/CacheStack.cs#L346

And here where the task which is executing the `getter` is not handing over the exception to the TCS in `UnlockWaitingTasks` but instead is setting the result to null.

https://github.com/TurnerSoftware/CacheTower/blob/2e3ac6d1789c283795686c3cfabc17537776567b/src/CacheTower/CacheStack.cs#L320

### How can it be reproduced?

I made a commit with a new Unit Test to reproduce this issue here: https://github.com/rgueldenpfennig/CacheTower/commit/6fd2673f9ee4c7c5dbda92290c3555a5263990b8

```csharp
[TestMethod]
public async Task GetOrSet_ConcurrentAccess_OnException()
{
	await using var cacheStack = new CacheStack(new[] { new MemoryCacheLayer() }, Array.Empty<ICacheExtension>());

	Internal.DateTimeProvider.UpdateTime();
	var getterCallCount = 0;

	var expectedException = new InvalidOperationException("Some exception");
	async Task act()
	{
		await cacheStack.GetOrSetAsync<int>(
			"GetOrSet_ConcurrentAccess_OnException",
			async _ =>
			{
				Interlocked.Increment(ref getterCallCount);
				await Task.Delay(250);
				throw expectedException;
			},
			new CacheSettings(TimeSpan.FromDays(2), TimeSpan.Zero)
		);
	}

	var tasks = Enumerable.Range(1, 2)
						  .Select(i => act())
						  .ToArray();

	try
	{
		await Task.WhenAll(tasks);
	}
	catch (Exception)
	{
	}

	Assert.AreEqual(1, getterCallCount);
	foreach (var task in tasks)
	{
		Assert.AreSame(expectedException, task.Exception.InnerException);
	}
}
```

In this case I would expect that the same exception is attached to the second task. Which is currently a NullReferenceException.

I'm also eager to provide a fix for this issue after we discussed a possible solution because I really like the caching implementation of CacheTower very much 😃👍

**Comment by Turnerj** [comment] 2021-11-05 02:41
Hey @rgueldenpfennig - thanks for raising this issue, your thorough details and your eagerness to want to provide the fix yourself! I really appreciate that!

I'll give your test a run locally and see what's going on to work out the steps forward.

**Comment by Turnerj** [comment] 2021-11-05 03:02
I've confirmed what you're seeing and yep, it seems that the problem is that line of code you've mentioned.

Assuming we want all tasks to essentially throw the same exception (which I think we do) and that there isn't an issue with that, we'd really just need to duplicate the `UnlockWaitingTasks` method with the second argument being an `Exception` instead, setting the exception on the task.

Open a PR with the fix and we can get it merged in and a new release of Cache Tower published!

**Closed** 2021-11-05 12:19 UTC
Labels: bug
